**Name** : Kamran Khan

**Batch** : B1

**Roll No** : 11

**Class** : TY CSE-AIML

<h1 align="center">Computing Lab - II | Experiment No - 2</h1>

**Aim**: Learn and practice NumPy's essential array operations: indexing, slicing, reshaping, axis manipulation, and transpose.

**Objective**: Through this experiment, develop a solid grasp of key NumPy array operations, including indexing, slicing, reshaping, as well as acquire proficiency in utilizing axis manipulation and transpose functionalities to effectively manipulate and analyze data arrays within the NumPy framework.

**Theory** : NumPy is a core Python library tailored for numerical computations, providing versatile n-dimensional arrays that excel in handling large datasets. It supports an array of mathematical functions, advanced indexing, and memory-efficient data types. Its robust features empower tasks in data analysis, simulations, and machine learning, underpinning Python's prominence in scientific computing.

In [3]:
import numpy as np

1. **Indexing**: Indexing refers to the process of accessing individual elements of an array using their position, known as the index. In Python, indexing starts from 0.

In [5]:
# Example: 1D Array

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Indexing in a 1D array
indexed_element = arr_1d[2]  # Accessing element at index 2 (zero-based)

# Print indexed element
print(indexed_element)

3


In [6]:
# Example: 2D Array

# Creating a 2D array (matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indexing in a 2D array
indexed_element_2d = arr_2d[1, 2]  # Accessing element at row 1, column 2

# Print indexed element
indexed_element_2d

6

In [7]:
# Example: 3D Array

# Creating a 3D array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

# Indexing in a 3D array
indexed_element_3d = arr_3d[0, 1, 2]  # Accessing element at (0, 1, 2)

# Print indexed element
indexed_element_3d

6

2. **Slicing**: Slicing allows us to extract a portion of an array by specifying a range of indices. The slicing syntax is [start:end], where the start index is included and the end index is excluded.

In [8]:
# Example: 1D Array Slicing

# Slicing in a 1D array
sliced_array = arr_1d[2:6]  # Extracting elements from index 2 to 5

# Print sliced array
sliced_array

array([3, 4, 5, 6])

In [9]:
# Example: 2D Array Slicing

# Slicing in a 2D array
sliced_submatrix = arr_2d[0:2, 1:3]  # Extracting rows 0 to 1, columns 1 to 2

# Print sliced submatrix
sliced_submatrix

array([[2, 3],
       [5, 6]])

In [10]:
# Example: 3D Array Slicing

# Slicing in a 3D array
sliced_subarray = arr_3d[:, 0:2, 0:2]  # Extracting all matrices, rows 0 to 1, columns 0 to 1

# Print sliced subarray
sliced_subarray

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

3. **Reshaping**: Reshaping involves changing the dimensions of an array while preserving the data. The `reshape` method is used for this purpose.

In [11]:
# Reshaping arrays
reshaped_1d = arr_1d.reshape(2, 5)  # Reshaping 1D array into a 2D array of shape (2, 5)
reshaped_2d = arr_2d.reshape(9)  # Reshaping 2D array into a 1D array of length 9

# Print reshaped arrays
reshaped_1d, reshaped_2d

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

4. **NumPy Axis** : In NumPy, the 'axis' parameter is used to specify the dimension along which operations are performed, such as mean, sum, etc. 

In [14]:
# Example using axis
arr_2d_mean_axis_0 = np.sum(arr_2d, axis=0)  # Calculate sum along rows (axis 0)
arr_2d_mean_axis_1 = np.sum(arr_2d, axis=1)  # Calculate sum along columns (axis 1)

# Print sum along axis 0 and axis 1
arr_2d_mean_axis_0, arr_2d_mean_axis_1

(array([12, 15, 18]), array([ 6, 15, 24]))

5. **NumPy Transpose** : The transpose operation swaps the rows and columns of a 2D array, effectively flipping it across its diagonal.

In [15]:
# Example using transpose
transposed_arr_2d = np.transpose(arr_2d)  # Transpose the 2D array

# Print transposed array
transposed_arr_2d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Conclusion**: Hence, We have learned and practiced NumPy's essential array operations: indexing, slicing, reshaping, axis manipulation, and transpose.